networks:
  default:
    external: 
      name: roboshop

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on: 
    - mongodb

  web:
    image: web:v1
    container_name: web
    ports:
    - 80:80
    depends_on: 
    - catalogue


  
           

     